#Site
name: Mr. Braz Tech
description: Este é um blog sobre desenvolvimento de sistemas distribuídos
meta_description: Ajudando desenvolvedores de backend a encontrarem as melhores soluções para sistemas distribuídos para que eles possam trabalhar em projetos incríveis e sem estresse.
logo: assets/images/logo.png
email: anderson.braz@gmail.com
time: 13/11/2018

baseurl: 
paginate: 10

google_analytics: UA-122758390-1
disqus: mrbraztech
markdown: kramdown
highlighter: rouge

mailchimp:
  newsletter: http://github.us13.list-manage.com/subscribe/post?u=53fdeff1bbaa9a91b2486aa86&id=63167cb18e

callToAction:
  title: "Série: Micro serviços direto das trincheiras"
  lead: "Junte-se a nós neste webinário ao vivo: Descubra os 7 melhores protocolos de comunicação para micro serviços e como eles resolvem os seus problemas"
  action: http://webinars.mrbraz.tech
  actionLabel: Quero me inscrever agora!

#hero
hero:
  image: /assets/images/head.jpg
  title: Encontre as melhores soluções para os seus problemas
  lead: Quer trabalhar em um projeto foda e sem estresse?
  actionLabel: ">> Descubra como <<"
  actionLink: /#articles
  actionTarget: _self

menu:
  glossario:
    label: Glossário
    link: /glossario
  about:
    label: Sobre
    link: /about
  contact:
    label: Contato
    link: /contact
  
# Authors
authors:
  braz:
    name: 'Braz'
    display_name: 'Mr.Braz'
    gravatar: '0f1f66c07f83cfa7ea461ca224023e37'
    email: 'anderson.braz@gmail.com'
    web: 'https://www.mrbraz.tech/'
    twitter: 'https://twitter.com/mrbraztech'
    description: 'Helping server-side developers find the best solutions for distributed system problems in order to work in a stress-free and awesome project.'

# Resources
resources:
  linkedin:
    name: Linkedin
    link: https://www.linkedin.com/in/mrbraztech

  slideshare:
    name: Slideshare
    link: http://slideshare.com/mrbrazjava
  github:
    name: Github
    link: http://gitbub.com/mrbraztech

# Partners
partners:
  jaya:
    name: Passionate Developers
    link: http://jaya.tech
  tdc:
    name: TDC
    link: http://thedevelopersconference.com.br
  code4life:
    name: Code4.Life
    link: https://code4.life
  cyborg:
    name: Cyborg Developer
    link: https://cyborgdeveloper.tech

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
